### ISSUE TITLE
The "target" folder is not wiped if it contains a "rls" folder

### ISSUE THREAD

**Issue by rhenescu** [mihai-dinculescu/cargo-wipe#12]
Running `cargo wipe target -w` removes the `debug`/`release` folders in `target`, but the `rls` folder (created by the Rust Language Server -- I use VS Code) is left untouched, so the `target` folder is not wiped in the end:
```
rust
├─ guessing_game
│  ├─ src
│  └─ target
│     └─ rls
│        └─ ...
└─ hello_cargo
   └─ src
```
Is this the intended behavior? Thank you!

**Comment by mihai-dinculescu** [comment]
No, that is not the indented behaviour.

However, some files might be left behind if there is lack of permissions, or if, more likely in your case, some files are currently in use.

If this is the case, there should be a visual indication.
![image](https://user-images.githubusercontent.com/9944681/102780301-94278600-438d-11eb-8d92-f4a50246fe54.png)

My guess is that Visual Code keeps some files inside `target/rls` open.
Can you please retry with Visual Code closed?

Maybe the last message, "All Clear!", should be changed so something else in this case.

**Comment by rhenescu** [comment]
I tried what you suggested, but didn't work even after rebooting, curiously:

```
/media/Home-Computer/rust$ cargo wipe target
[DRY RUN] Recursively searching for all "target" folders in /media/Home-Computer/rust...

Nothing found!
```

After some tinkering, I suspect the behavior is caused by the [Rust](https://marketplace.visualstudio.com/items?itemName=rust-lang.rust) plugin. Switching to [rust-analyzer](https://marketplace.visualstudio.com/items?itemName=matklad.rust-analyzer) solved the problem.
