### ISSUE TITLE
Dry run gives wrong help

### ISSUE THREAD

**Issue by sts10** [mihai-dinculescu/cargo-wipe#18]
Just ran `cargo wipe rust` for a dry run. At the end, the message displayed reads `Run cargo wipe target -w to wipe all folders found. USE WITH CAUTION!`

I'm assuming it's supposed to recommend `cargo wipe rust -w`?

**Comment by mihai-dinculescu** [comment]
`rust` and `target` are supposed to be aliases, so the output will be the same with either.

However, I do realize why this is confusing, so in version 0.3.2 the help has been fixed and the `target` and `node_modules` aliases have been deprecated.

Thank you for reporting this!
