### ISSUE TITLE
Feature suggestion: --dry-run

### ISSUE THREAD

**Issue by steveswing** [mihai-dinculescu/cargo-wipe#2]
Please consider adding a --dry-run flag that will find, list, summarize but not delete the target folders that will be deleted by cargo wipe if not run with the --dry-run flag.

The summary could include the number of files and size on disk that will be recovered.

**Comment by steveswing** [comment]
I may have misunderstood that by default cargo-wipe always runs in --dry-run mode unless the -w flag is provided. If that's the case then this issue can be closed.

**Comment by mihai-dinculescu** [comment]
> 
> 
> I may have misunderstood that by default cargo-wipe always runs in --dry-run mode unless the -w flag is provided. If that's the case then this issue can be closed.

Your assumption is correct! Are the docs / cli help not clear? Is there anything I can do to make it more obvious?

**Comment by steveswing** [comment]
No, I just need to read more carefully and try things out before opening an issue. Although, perhaps if you include `-w` in the list of flags people like me could miss the initial description but still understand.

Is the usage:

`cargo wipe <SUBCOMMAND> <FLAGS>` ?

It would be nice to be able to use both `target` and `node_modules` subcommands at the same time?

**Comment by mihai-dinculescu** [comment]
> 
> 
> No, I just need to read more carefully and try things out before opening an issue. Although, perhaps if you include `-w` in the list of flags people like me could miss the initial description but still understand.
> 
> Is the usage:
> 
> `cargo wipe <SUBCOMMAND> <FLAGS>` ?

This is missing for now because of a limitation in `structopt`. I have added a TODO item to look into it in more detail.

> 
> It might be nice to be able to use both `target` and `node_modules` subcommands at the same time.

Thanks for the suggestion, I have added a TODO item for consideration.
